name: EzChatMod
main: jasonw4331\EzChatMod\Main
src-namespace-prefix: jasonw4331\EzChatMod
version: 3.0.0
api: [4.0.0, 5.0.0]
description: "A plugin for blocking server chat spam"
author: "jasonw4331"